@extends('layouts.admin') @section('title',$event->exists?'Chỉnh sửa bài viết':'Thêm bài viết mới') @section('content')
<style>.form-grid{display:grid;grid-template-columns:1fr 320px;gap:20px;align-items:start}.tab-btns{display:flex;gap:6px;margin-bottom:16px}.tab-btn{padding:7px 15px;border-radius:8px;border:1.5px solid var(--border);background:#f8fafc;font-size:.8125rem;font-weight:500;color:var(--muted);cursor:pointer}.tab-btn.active{background:var(--accent);border-color:var(--accent);color:#fff}.tab-panel{display:none}.tab-panel.active{display:block}.thumb-preview{width:100%;aspect-ratio:16/9;border-radius:10px;border:2px dashed var(--border);background:#f8fafc;display:flex;align-items:center;justify-content:center;color:var(--muted);overflow:hidden}.thumb-preview img{width:100%;height:100%;object-fit:cover}.img-gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(90px,1fr));gap:10px;margin-top:12px}.img-item{position:relative}.img-item img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:8px;border:1px solid var(--border)}.image-delete{width:100%;margin-top:4px;border:0;border-radius:6px;padding:5px;background:#fff1f2;color:#be123c;cursor:pointer}.hidden-form{display:none}.char-count{font-size:.72rem;color:var(--muted);text-align:right;margin-top:3px}.save-actions{display:flex;gap:8px;margin-bottom:16px;justify-content:flex-end}.rich-editor-wrap{border:1.5px solid var(--border);border-radius:10px;overflow:hidden;background:#fff}.rich-editor-toolbar{display:flex;gap:7px;align-items:center;padding:8px 10px;border-bottom:1px solid var(--border);background:#f8fafc}.editor-tool{border:1px solid #dbe2ea;border-radius:7px;background:#fff;color:#334155;padding:7px 11px;font:inherit;font-size:.78rem;font-weight:600;cursor:pointer}.editor-tool:hover{border-color:var(--accent);color:var(--accent)}.rich-editor{min-height:260px;padding:13px 14px;line-height:1.7;outline:0;white-space:normal}.rich-editor:focus{box-shadow:inset 0 0 0 2px rgba(244,63,117,.1)}.rich-editor:empty:before{content:attr(data-placeholder);color:#94a3b8}.rich-editor a{color:#2563eb;text-decoration:underline}.link-help{display:block;margin-top:6px;color:var(--muted)}.link-dialog{width:min(520px,calc(100% - 28px));border:0;border-radius:14px;padding:0;box-shadow:0 24px 70px #0f172a4d}.link-dialog::backdrop{background:#0f172a66}.link-dialog-body{padding:22px}.link-dialog h2{margin:0 0 6px;font-size:1.15rem}.link-dialog p{margin:0 0 17px;color:var(--muted);font-size:.82rem}.link-dialog .form-group{margin-bottom:13px}.link-dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.selected-keyword{display:inline-block;max-width:100%;padding:4px 8px;border-radius:6px;background:#fff1f5;color:#be185d;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;vertical-align:middle}@media(max-width:900px){.form-grid{grid-template-columns:1fr}}</style>
<style>.form-grid{grid-template-columns:minmax(0,1fr);max-width:960px;margin:0 auto}.form-grid>aside{display:grid;grid-template-columns:1fr;gap:16px}.save-actions{max-width:960px;margin-left:auto;margin-right:auto}.content-step{padding-top:20px;margin-top:20px;border-top:1px solid var(--border)}.content-step>.form-label{font-size:.9rem;color:#1e293b}.tab-btns{position:sticky;top:72px;z-index:4;padding:8px;border:1px solid var(--border);border-radius:11px;background:#fff;box-shadow:0 6px 18px #0f172a0d}@media(max-width:640px){.save-actions{flex-wrap:wrap}.save-actions .btn-primary-custom{flex:1;justify-content:center}.tab-btns{position:static}}</style>
<style>.img-gallery{grid-template-columns:1fr;gap:16px}.img-item,.new-image-description{display:grid;grid-template-columns:240px minmax(0,1fr);gap:16px;align-items:start;padding:14px;border:1px solid var(--border);border-radius:12px;background:#fff}.img-item>img,.new-image-description>img{width:100%;aspect-ratio:16/10;object-fit:cover;border-radius:9px}.image-fields{min-width:0}.image-fields label{display:block;margin:10px 0 5px;font-size:.76rem;font-weight:700;color:#475569}.image-fields label:first-child{margin-top:0}.image-description{width:100%;border:1px solid var(--border);border-radius:8px;padding:8px 10px;font:inherit;font-size:.78rem}.image-rich-editor{min-height:130px}.image-fields .rich-editor-toolbar{padding:6px 8px}.image-fields .editor-tool{padding:5px 8px}.new-image-descriptions{display:grid;gap:12px;margin-top:12px}.new-image-description{background:#f8fafc}.new-image-description strong{display:block;margin-bottom:8px;font-size:.76rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.save-actions .btn-primary-custom[type=submit]{min-width:160px}@media(max-width:700px){.img-item,.new-image-description{grid-template-columns:1fr}.img-item>img,.new-image-description>img{max-height:260px}}</style>
<template id="event-price-fields"><div class="form-row"><div class="form-group"><label class="form-label">Giá gốc (VNĐ)</label><input class="form-control-custom" type="number" min="0" step="1000" name="original_price" value="{{ old('original_price',$event->original_price) }}" placeholder="Để trống: Giá liên hệ"></div><div class="form-group"><label class="form-label">Giá giảm (VNĐ)</label><input class="form-control-custom" type="number" min="0" step="1000" name="sale_price" value="{{ old('sale_price',$event->sale_price) }}" placeholder="Không bắt buộc"></div></div><small class="form-help">Nếu nhập cả hai mức giá, website sẽ gạch giá gốc và làm nổi bật giá giảm.</small></template>
<div class="save-actions"><a class="btn-primary-custom" style="background:#64748b" href="{{ route('admin.events') }}">← Danh sách</a><button form="event-form" type="submit" class="btn-primary-custom">💾 Lưu bài viết</button></div>
<form id="event-form" method="post" enctype="multipart/form-data" action="{{ route('admin.events.save',$event->exists?$event:null) }}" data-confirm="Xác nhận lưu nội dung bài viết và các thiết lập SEO?" data-confirm-title="Lưu bài viết">@csrf<div class="form-grid"><div><div class="tab-btns"><button type="button" class="tab-btn active" data-tab="basic">📝 Cơ bản</button><button type="button" class="tab-btn" data-tab="images">🖼️ Hình ảnh</button><button type="button" class="tab-btn" data-tab="seo">🔍 SEO</button></div>
<section id="tab-basic" class="tab-panel active section-card"><div class="form-group"><label class="form-label">Tiêu đề <span class="required">*</span></label><input class="form-control-custom" name="title" maxlength="255" value="{{ old('title',$event->title) }}" required placeholder="Nhập tiêu đề bài viết..."></div><div class="form-group"><label class="form-label">Slug URL</label><div class="input-prefix"><span>/bai-viet/</span><input name="slug" value="{{ old('slug',$event->slug) }}" placeholder="Tự tạo nếu để trống"></div><small class="form-help">Chữ thường, không dấu, phân cách bằng dấu gạch ngang.</small></div><div class="form-group"><label class="form-label">Tóm tắt</label><textarea class="form-control-custom textarea" name="summary" rows="3" maxlength="500" placeholder="Mô tả ngắn ở danh sách bài viết...">{{ old('summary',$event->summary) }}</textarea></div><div class="form-group"><label class="form-label">Nội dung chi tiết</label><div class="rich-editor-wrap"><div class="rich-editor-toolbar"><button class="editor-tool" id="insert-link" type="button">🔗 Chèn liên kết</button><button class="editor-tool" id="remove-link" type="button">Bỏ liên kết</button></div><div class="rich-editor" id="content-editor" contenteditable="true" role="textbox" aria-multiline="true" data-placeholder="Nội dung đầy đủ của bài viết...">{!! \App\Support\PostContent::sanitize(old('content',$event->content)) !!}</div></div><textarea id="content-input" name="content" hidden>{{ old('content',$event->content) }}</textarea><small class="link-help">Bôi đen từ khóa cần liên kết, chọn “Chèn liên kết”, rồi chọn một bài viết nội bộ hoặc nhập URL.</small></div><div class="form-group"><label class="form-label">Tiêu đề sau hình ảnh</label><input class="form-control-custom" name="after_gallery_title" maxlength="255" value="{{ old('after_gallery_title',$event->after_gallery_title) }}" placeholder="Ví dụ: Kinh nghiệm chuẩn bị cho sự kiện"></div><div class="form-group"><label class="form-label">Nội dung sau hình ảnh</label><textarea class="form-control-custom textarea" name="after_gallery_content" rows="10" placeholder="Nội dung bổ sung hiển thị bên dưới thư viện ảnh...">{{ old('after_gallery_content',$event->after_gallery_content) }}</textarea><small class="form-help">Nội dung này hiển thị sau toàn bộ hình ảnh. Xuống dòng hai lần để tách đoạn; để trống nếu không muốn hiển thị.</small></div><div class="form-row"><div class="form-group"><label class="form-label">Ngày tổ chức</label><input class="form-control-custom" type="datetime-local" name="event_date" value="{{ old('event_date',optional($event->event_date)->format('Y-m-d\TH:i')) }}"></div><div class="form-group"><label class="form-label">Địa điểm</label><input class="form-control-custom" name="location" value="{{ old('location',$event->location) }}" placeholder="TP. Hồ Chí Minh"></div></div></section>
<section id="tab-images" class="tab-panel section-card"><div class="form-group"><label class="form-label">Ảnh đại diện</label><div class="thumb-preview" id="thumb-preview">@if($event->thumbnail)<img src="{{ Str::startsWith($event->thumbnail,'thumbnails/')?asset('storage/'.$event->thumbnail):asset('uploads/thumbnails/'.$event->thumbnail) }}">@else<span>📷 Chọn ảnh đại diện</span>@endif</div><input class="form-control-custom" style="margin-top:10px" type="file" name="thumbnail" accept="image/*"></div>@if($event->images->count())<div class="form-group"><label class="form-label">Thư viện ảnh hiện có</label><div class="img-gallery">@foreach($event->images as $image)<div class="img-item"><img src="{{ asset('storage/'.$image->image_path) }}" alt="{{ $image->alt_text }}"><div class="image-fields"><label>Tiêu đề ảnh</label><input class="image-description" name="existing_image_titles[{{ $image->id }}]" maxlength="255" value="{{ old('existing_image_titles.'.$image->id,$image->title) }}" placeholder="Tiêu đề riêng của ảnh"><label>Nội dung ảnh</label><div class="rich-editor-wrap"><div class="rich-editor-toolbar"><button class="editor-tool js-insert-link" data-editor-id="image-content-{{ $image->id }}" type="button">🔗 Chèn liên kết</button><button class="editor-tool js-remove-link" data-editor-id="image-content-{{ $image->id }}" type="button">Bỏ liên kết</button></div><div class="rich-editor image-rich-editor js-content-editor" id="image-content-{{ $image->id }}" data-input-id="image-content-input-{{ $image->id }}" contenteditable="true" role="textbox" aria-multiline="true" data-placeholder="Nội dung mô tả riêng cho ảnh...">{!! \App\Support\PostContent::sanitize(old('existing_image_contents.'.$image->id,$image->content)) !!}</div></div><textarea id="image-content-input-{{ $image->id }}" name="existing_image_contents[{{ $image->id }}]" hidden>{{ old('existing_image_contents.'.$image->id,$image->content) }}</textarea><label>Alt ảnh</label><input class="image-description" name="existing_alt_texts[{{ $image->id }}]" maxlength="255" value="{{ old('existing_alt_texts.'.$image->id,$image->alt_text) }}" placeholder="Mô tả Alt dành cho SEO"><button type="submit" form="delete-image-{{ $image->id }}" class="image-delete">× Xóa ảnh</button></div></div>@endforeach</div></div>@endif<div class="form-group"><label class="form-label">Thêm ảnh phụ</label><input class="form-control-custom" type="file" name="extra_images[]" accept="image/*" multiple><small class="form-help">Không bắt buộc. Có thể để trống hoặc chọn tối đa 12 ảnh, tối đa 5MB mỗi ảnh.</small><div class="new-image-descriptions" id="new-image-descriptions"></div></div></section>
<section id="tab-seo" class="tab-panel section-card"><div class="form-group"><label class="form-label">Meta Title</label><input class="form-control-custom" name="meta_title" maxlength="255" value="{{ old('meta_title',$event->meta_title) }}" placeholder="Để trống sẽ dùng tiêu đề chính"><div class="char-count">Khuyến nghị 50-60 ký tự</div></div><div class="form-group"><label class="form-label">Meta Description</label><textarea class="form-control-custom textarea" name="meta_description" rows="3" maxlength="255" placeholder="Mô tả hiển thị trên Google...">{{ old('meta_description',$event->meta_description) }}</textarea><div class="char-count">Khuyến nghị 140-160 ký tự</div></div><div style="border:1px solid var(--border);border-radius:10px;padding:16px;background:#f8fafc"><small style="color:var(--muted)">🔎 Xem trước đường dẫn Google</small><div style="color:#1a0dab;font-size:1rem;margin-top:8px">{{ old('meta_title',$event->meta_title) ?: old('title',$event->title) ?: 'Tiêu đề bài viết' }}</div><div style="color:#15803d;font-size:.78rem">{{ url('/bai-viet') }}/{{ old('slug',$event->slug) }}</div><div style="color:#545454;font-size:.8rem;margin-top:4px">{{ old('meta_description',$event->meta_description) ?: old('summary',$event->summary) }}</div></div></section></div>
<aside><section class="section-card"><h2 class="section-title" style="margin-bottom:16px">Cài đặt đăng</h2><div class="form-group"><label class="form-label">Trạng thái</label><select class="form-control-custom" name="status">@foreach(['draft'=>'📄 Bản nháp','published'=>'✅ Đã đăng','archived'=>'🗃️ Lưu trữ'] as $v=>$n)<option value="{{ $v }}" {{ old('status',$event->status?:'draft')===$v?'selected':'' }}>{{ $n }}</option>@endforeach</select></div><div class="form-group"><label class="form-label">Dịch vụ / danh mục</label><select class="form-control-custom" name="category_id"><option value="">- Chọn danh mục -</option>@foreach($categories as $cat)<option value="{{ $cat->id }}" {{ (string)old('category_id',$event->category_id)===(string)$cat->id?'selected':'' }}>{{ $cat->name }}</option>@endforeach</select></div></section><section class="section-card"><h2 class="section-title">Gợi ý SEO</h2><p style="font-size:.78rem;color:var(--muted);line-height:1.7;margin-top:10px">Tiêu đề chứa tên dịch vụ, slug ngắn gọn, ảnh rõ nét và nội dung mô tả chi tiết sẽ giúp Google hiểu bài tốt hơn.</p></section></aside></div></form>
@foreach($event->images as $image)<form id="delete-image-{{ $image->id }}" method="post" action="{{ route('admin.images.delete',$image) }}" class="hidden-form" data-confirm="Xóa ảnh này khỏi bài viết?" data-confirm-title="Xác nhận xóa ảnh">@csrf @method('delete')</form>@endforeach
<dialog class="link-dialog" id="link-dialog"><form class="link-dialog-body" method="dialog" id="link-form"><h2>Gắn liên kết vào từ khóa</h2><p>Từ khóa đã chọn: <span class="selected-keyword" id="selected-keyword"></span></p><div class="form-group"><label class="form-label" for="internal-link">Bài viết nội bộ</label><select class="form-control-custom" id="internal-link"><option value="">— Chọn bài viết —</option>@foreach($linkableEvents as $linkEvent)<option value="{{ route('event', $linkEvent, false) }}">{{ $linkEvent->title }}</option>@endforeach</select></div><div class="form-group"><label class="form-label" for="custom-link">Hoặc nhập đường dẫn</label><input class="form-control-custom" id="custom-link" type="text" inputmode="url" placeholder="/bai-viet/slug hoặc https://..."><small class="form-help">Đường dẫn nhập tay được ưu tiên nếu cả hai trường đều có giá trị.</small></div><div class="link-dialog-actions"><button class="editor-tool" type="button" id="cancel-link">Hủy</button><button class="btn-primary-custom" type="submit">Gắn liên kết</button></div></form></dialog>
<script>
const priceFieldsTemplate=document.getElementById('event-price-fields');const summaryGroup=document.querySelector('[name="summary"]')?.closest('.form-group');if(priceFieldsTemplate&&summaryGroup)summaryGroup.after(priceFieldsTemplate.content.cloneNode(true));
document.querySelectorAll('.tab-btn').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));button.classList.add('active');document.getElementById('tab-'+button.dataset.tab).classList.add('active')})});document.querySelector('input[name="thumbnail"]')?.addEventListener('change',function(){const file=this.files[0];if(!file)return;document.getElementById('thumb-preview').innerHTML='<img src="'+URL.createObjectURL(file)+'" alt="Xem trước">';});
const extraImagesInput=document.querySelector('input[name="extra_images[]"]');
const newImageDescriptions=document.getElementById('new-image-descriptions');
extraImagesInput?.addEventListener('change',function(){newImageDescriptions.replaceChildren();Array.from(this.files).forEach((file,index)=>{const editorId='new-image-content-'+index;const inputId='new-image-content-input-'+index;const row=document.createElement('div');row.className='new-image-description';const preview=document.createElement('img');preview.src=URL.createObjectURL(file);preview.alt='Xem trước '+file.name;const fields=document.createElement('div');fields.className='image-fields';const name=document.createElement('strong');name.textContent=file.name;const titleLabel=document.createElement('label');titleLabel.textContent='Tiêu đề ảnh';const title=document.createElement('input');title.className='image-description';title.name='image_titles['+index+']';title.maxLength=255;title.placeholder='Tiêu đề riêng của ảnh';const contentLabel=document.createElement('label');contentLabel.textContent='Nội dung ảnh';const editorWrap=document.createElement('div');editorWrap.className='rich-editor-wrap';const toolbar=document.createElement('div');toolbar.className='rich-editor-toolbar';const insertButton=document.createElement('button');insertButton.type='button';insertButton.className='editor-tool js-insert-link';insertButton.dataset.editorId=editorId;insertButton.textContent='🔗 Chèn liên kết';const removeButton=document.createElement('button');removeButton.type='button';removeButton.className='editor-tool js-remove-link';removeButton.dataset.editorId=editorId;removeButton.textContent='Bỏ liên kết';toolbar.append(insertButton,removeButton);const editor=document.createElement('div');editor.id=editorId;editor.className='rich-editor image-rich-editor js-content-editor';editor.dataset.inputId=inputId;editor.contentEditable='true';editor.setAttribute('role','textbox');editor.setAttribute('aria-multiline','true');editor.dataset.placeholder='Nội dung mô tả riêng cho ảnh...';const hidden=document.createElement('textarea');hidden.id=inputId;hidden.name='image_contents['+index+']';hidden.hidden=true;editorWrap.append(toolbar,editor);const altLabel=document.createElement('label');altLabel.textContent='Alt ảnh';const alt=document.createElement('input');alt.className='image-description';alt.name='alt_texts['+index+']';alt.maxLength=255;alt.placeholder='Mô tả Alt dành cho SEO';fields.append(name,titleLabel,title,contentLabel,editorWrap,hidden,altLabel,alt);row.append(preview,fields);newImageDescriptions.append(row)})});
const eventForm=document.getElementById('event-form');
const contentEditor=document.getElementById('content-editor');
const linkDialog=document.getElementById('link-dialog');
const internalLink=document.getElementById('internal-link');
const customLink=document.getElementById('custom-link');
let selectedRange=null;
let selectedEditor=null;

const basicPanel=document.getElementById('tab-basic');
const imagesPanel=document.getElementById('tab-images');
const thumbnailGroup=document.querySelector('input[name="thumbnail"]')?.closest('.form-group');
const mainContentGroup=contentEditor.closest('.form-group');
const afterTitleGroup=document.querySelector('input[name="after_gallery_title"]')?.closest('.form-group');
const afterContentGroup=document.querySelector('[name="after_gallery_content"]')?.closest('.form-group');
if(thumbnailGroup&&mainContentGroup)mainContentGroup.before(thumbnailGroup);
if(imagesPanel&&afterTitleGroup&&afterContentGroup)imagesPanel.append(afterTitleGroup,afterContentGroup);
document.querySelector('[data-tab="basic"]').textContent='1. Ảnh chính & nội dung';
document.querySelector('[data-tab="images"]').textContent='2. Ảnh phụ & nội dung sau ảnh';
document.querySelector('[data-tab="seo"]').textContent='3. SEO';
if(thumbnailGroup){thumbnailGroup.classList.add('content-step');thumbnailGroup.querySelector('.form-label').textContent='1. Ảnh chính / ảnh đại diện'}
mainContentGroup.classList.add('content-step');mainContentGroup.querySelector('.form-label').textContent='2. Nội dung chính';
if(afterTitleGroup){afterTitleGroup.classList.add('content-step');afterTitleGroup.querySelector('.form-label').textContent='4. Tiêu đề nội dung sau ảnh'}
if(afterContentGroup)afterContentGroup.querySelector('.form-label').textContent='5. Nội dung sau ảnh';
const existingGalleryLabel=imagesPanel?.querySelector('.img-gallery')?.closest('.form-group')?.querySelector('.form-label');if(existingGalleryLabel)existingGalleryLabel.textContent='3. Ảnh phụ hiện có';
const extraImagesLabel=document.querySelector('input[name="extra_images[]"]')?.closest('.form-group')?.querySelector('.form-label');if(extraImagesLabel)extraImagesLabel.textContent='3. Thêm ảnh phụ';

const allContentEditors=()=>[contentEditor,...document.querySelectorAll('.js-content-editor')];
const rangeIsInEditor=(range,editor)=>range&&editor&&editor.contains(range.startContainer)&&editor.contains(range.endContainer);
const syncEditor=editor=>{const inputId=editor.dataset.inputId||(editor===contentEditor?'content-input':null);const input=inputId?document.getElementById(inputId):null;if(input)input.value=editor.innerHTML};
const rememberSelection=()=>{const selection=window.getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);const editor=allContentEditors().find(item=>rangeIsInEditor(range,item));if(editor){selectedEditor=editor;selectedRange=range.cloneRange()}};
const restoreSelection=()=>{if(!rangeIsInEditor(selectedRange,selectedEditor))return false;const selection=window.getSelection();selection.removeAllRanges();selection.addRange(selectedRange);return true};

document.addEventListener('selectionchange',rememberSelection);
document.addEventListener('input',event=>{if(event.target.matches('#content-editor,.js-content-editor'))syncEditor(event.target)});
eventForm.addEventListener('submit',()=>allContentEditors().forEach(syncEditor));
document.addEventListener('mousedown',event=>{if(event.target.closest('#insert-link,#remove-link,.js-insert-link,.js-remove-link'))event.preventDefault()});
document.addEventListener('click',event=>{const insertButton=event.target.closest('#insert-link,.js-insert-link');if(insertButton){const editorId=insertButton.dataset.editorId;const expectedEditor=editorId?document.getElementById(editorId):contentEditor;rememberSelection();if(!selectedRange||selectedRange.collapsed||selectedEditor!==expectedEditor||!rangeIsInEditor(selectedRange,selectedEditor)){alert('Hãy bôi đen từ khóa trong đúng ô nội dung trước khi chèn liên kết.');return}document.getElementById('selected-keyword').textContent=selectedRange.toString();internalLink.value='';customLink.value='';customLink.setCustomValidity('');linkDialog.showModal();return}const removeButton=event.target.closest('#remove-link,.js-remove-link');if(removeButton){const editorId=removeButton.dataset.editorId;const expectedEditor=editorId?document.getElementById(editorId):contentEditor;rememberSelection();if(selectedEditor!==expectedEditor||!restoreSelection())return;const anchors=Array.from(selectedEditor.querySelectorAll('a')).filter(anchor=>{try{return selectedRange.intersectsNode(anchor)}catch(error){return false}});anchors.forEach(anchor=>anchor.replaceWith(...anchor.childNodes));syncEditor(selectedEditor);selectedRange=null;selectedEditor.focus()}});

document.getElementById('cancel-link').addEventListener('click',()=>linkDialog.close());
document.getElementById('link-form').addEventListener('submit',event=>{event.preventDefault();const url=customLink.value.trim()||internalLink.value;if(!url){customLink.setCustomValidity('Vui lòng chọn hoặc nhập một đường dẫn.');customLink.reportValidity();return}customLink.setCustomValidity('');if(!restoreSelection()||selectedRange.collapsed){linkDialog.close();alert('Vùng từ khóa đã chọn không còn hợp lệ. Vui lòng bôi đen lại từ khóa.');return}const link=document.createElement('a');link.setAttribute('href',url);link.appendChild(selectedRange.extractContents());selectedRange.insertNode(link);const selection=window.getSelection();selection.removeAllRanges();const afterLink=document.createRange();afterLink.setStartAfter(link);afterLink.collapse(true);selection.addRange(afterLink);selectedRange=afterLink.cloneRange();syncEditor(selectedEditor);linkDialog.close();selectedEditor.focus()});
</script>@endsection
