@extends('layouts.site')
@section('title',$event->meta_title ?: $event->title.' — '.$settings['brand_name'])
@section('description',$event->meta_description ?: Str::limit($event->summary,155,''))
@section('canonical',route('event',$event))
@section('og_type','article')
@if($event->thumbnail) @section('og_image',Str::startsWith($event->thumbnail,'thumbnails/')?asset('storage/'.$event->thumbnail):asset('uploads/thumbnails/'.$event->thumbnail)) @endif
@section('content')
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$event->title,'description'=>$event->meta_description ?: $event->summary,'datePublished'=>optional($event->created_at)->toAtomString(),'dateModified'=>optional($event->updated_at)->toAtomString(),'author'=>['@type'=>'Organization','name'=>$settings['brand_name']],'publisher'=>['@type'=>'Organization','name'=>$settings['brand_name']],'mainEntityOfPage'=>route('event',$event)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>
<x-navigation-trail :category="$event->category" :current="$event->title"/><article class="article"><div class="article-category">{{ optional($event->category)->name }}</div><h1>{{ $event->title }}</h1><p class="meta">Đăng ngày {{ $event->created_at->format('d/m/Y') }} · {{ optional($event->event_date)->format('d/m/Y H:i') }} · 📍 {{ $event->location }} · 👁 {{ $event->view_count }}</p>@if($event->thumbnail)<img class="cover" src="{{ Str::startsWith($event->thumbnail,'thumbnails/')?asset('storage/'.$event->thumbnail):asset('uploads/thumbnails/'.$event->thumbnail) }}" alt="{{ $event->title }}">@endif<p class="lead">{{ $event->summary }}</p><div class="prose">{!! nl2br(e($event->content)) !!}</div>@foreach($event->images as $img)<figure><img class="cover" loading="lazy" src="{{ asset('storage/'.$img->image_path) }}" alt="{{ $img->alt_text ?: $event->title }}">@if($img->alt_text)<figcaption>{{ $img->alt_text }}</figcaption>@endif</figure>@endforeach<div class="event-actions"><a class="btn" href="tel:{{ preg_replace('/\s+/','',$settings['phone']) }}">☎ Gọi {{ $settings['phone'] }}</a>@if($settings['facebook'])<a class="btn-secondary" href="{{ $settings['facebook'] }}" target="_blank" rel="noopener">Nhắn Facebook</a>@endif</div></article>@endsection
